version: "3.9"
services:
  app:
    image: "node:18.5.0-alpine3.15"
    #user: "node"
    command: >
      sh -c "
             npm install -g npm@latest &&
             npm install -g create-react-app &&
             create-react-app prueba &&
             cd prueba &&
             npm start"
    volumes:
      - "./:/app:cached"
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true